apiVersion: v1
kind: Namespace
metadata:
  name: bar
  labels:
    environment-id: env_97db6157-d323-4d24-9640-9aac19380a7b
    project-id: project_263dda5d-b085-43ab-a63f-9da65c09ef8f
    project-name: PercyJ
    environment-name: prod
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
